### ISSUE TITLE
Ltx-video finetuning

### ISSUE THREAD

**Issue by neph1** [tdrussell/diffusion-pipe#10]
Hi,
Thank you for this framework.

Has anyone been able to train ltx-video using this, and would they kindly consider sharing the setup?
I spent some time yesterday modifying config (and code), but was not able to make it run, possibly due to the updates they've made to ltx in the last couple of days?

Thank you.

And sorry for raising an issue for this. If there is another forum suitable for the discussion, please direct me there.

Edit: I'm on 0.32.0.dev0, btw. But there seem to be more open PR's related to ltx, so that may be what's causing my problems.

**Comment by tdrussell** [comment]
LTX training works on my environment, with Diffusers 0.31.0 and using the [LTX-Video huggingface repo](https://huggingface.co/Lightricks/LTX-Video) at commit a5ab70cf0b89a0b90dfafe3556c24f1b4767bdc8. I see the model has several updates since then, maybe something broke on newer version, or with Diffusers. I'll pull and update everything when I get time and fix any errors. Might take a few days before I get to it.

**Comment by neph1** [comment]
Or my version is too old :sweat_smile: 
Thanks for the confirmation, then I'll keep on trying.
