### ISSUE TITLE
Support for Torchrun Script Instead of Deepspeed?

### ISSUE THREAD

**Issue by radna0** [tdrussell/diffusion-pipe#22]
I'm running on non-Nvidia Hardware, would be nice to have a torchrun script not using deepspeed

**Comment by tdrussell** [comment]
I doubt this will ever happen. The entire framework of the training script is built around deepspeed's pipeline parallelism implementation.

**Comment by radna0** [comment]
@tdrussell  What about FSDP? https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html

**Comment by tdrussell** [comment]
That is a different kind of multi-GPU parallelization technique. Deepspeed is a core requirement for this training script. It is built around using deepspeed's libraries and APIs to do pipeline parallelism.

When you say deepspeed doesn't work on non-Nvidia hardware (I guess AMD?), did you try it? I ask because Deepspeed internal code is like 99% vanilla Pytorch. I'm not sure what deepspeed would be doing that would cause incompatibility on non-Nvidia hardware, that any other way of implementing pipeline parallelism wouldn't also have.

**Comment by radna0** [comment]
Oh right, I'm mostly working with TPUs. I believe deepspeed relies on some C++/CUDA ops so it's not compatible there. I would probably have to port it to Pytorch xla, which is what enables Pytorch on TPUs.

**Comment by radna0** [comment]
@tdrussell Closing this issue, as I got DeepSpeed somewhat running on XLA/TPUs. Mentioning this latest issue: https://github.com/tdrussell/diffusion-pipe/issues/25
