### ISSUE TITLE
More frequent model saving options for larger datasets possible?

### ISSUE THREAD

**Issue by steve84wien** [tdrussell/diffusion-pipe#23]
I'm planning to train on a larger dataset of approximately 2,000 style images.  I'm concerned that saving only once per epoch might not give me enough checkpoints to find the optimal stopping point. Is there a recommended way to save weights more frequently like "save_every_n_steps"?

**Comment by tdrussell** [comment]
There is a TODO to enable this: https://github.com/tdrussell/diffusion-pipe/blob/dc7b9ba127d2afd5adf72c9d5d444c389165697e/utils/saver.py#L160

Actually, looking at the code, I'm not sure why it's even commented out. Probably because I wanted to add a check that only one of save_every_n_epochs and save_every_n_steps is set? It should probably just work if you uncomment those lines and set save_every_n_steps. But if you do this I would do a quick test with a low value first to confirm it works right.

**Comment by steve84wien** [comment]
Thanks! 
I am getting the following error after uncommenting the suggested lines and adding save_every_n_step=200 to the config

`Traceback (most recent call last):
  File "/workspace/diffusion-pipe/train.py", line 25, in <module>
    import utils.saver
  File "/workspace/diffusion-pipe/utils/saver.py", line 161
    if step % self.config['save_every_n_steps'] == 0 or should_manually_save:
                                                                             ^
IndentationError: unindent does not match any outer indentation level
[2024-12-21 11:08:57,371] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 8782
[2024-12-21 11:08:57,371] [ERROR] [launch.py:325:sigkill_handler] ['/root/miniconda3/envs/diffusion-pipe/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1`
